---
title: "Case Study"
author: "Jessica Flynn"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)
library(leaflet)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r add_data}
data(nyc_airbnb)
```

## Brainstorm some questions

* what is the best Airbnb in Staten island for less than $100?
* what price range is popular in each borough ? most rented ?
* what apartment features are related to price?
* cheapest room type in each neighborhood ?
* hosts have higher ratings?

data cleaning 

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2)
```

## Answer some questions 

```{r}
nyc_airbnb %>%
  count(neighbourhood_group, room_type) %>% 
  pivot_wider(names_from = room_type, 
              values_from = n)
```

```{r}
nyc_airbnb %>% 
  group_by(neighbourhood_group, room_type) %>% 
  summarize(mean_price = mean(price))
```


```{r}
nyc_airbnb %>% 
  filter(price < 1000) %>% 
  ggplot(aes(x = neighbourhood_group, y = price)) + 
  geom_boxplot()
```

```{r}
nyc_airbnb %>% 
  filter(neighbourhood_group == "Manhattan") %>% 
  count(neighbourhood)
```


```{r}
nyc_airbnb %>% 
  filter(price < 1000, 
         neighbourhood_group == "Manhattan") %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>%
  ggplot(aes(x = neighbourhood, y = price)) + 
  geom_boxplot() + 
  coord_flip()
```

```{r}
nyc_airbnb %>% 
  sample_n(1000) %>% 
  ggplot(aes(x = lat, y = long, color = price)) + 
  geom_point()
```

## Create a leaflet map

```{r}

pal <- colorNumeric("viridis", nyc_airbnb %>% pull(stars))

nyc_airbnb %>% 
  sample_n(1000) %>% 
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~lat, ~long, radius = 1, color = ~pal(stars))
```



```{r}
  nyc_airbnb %>% 
  group_by(neighbourhood_group) %>%
  mutate(min_price = min(price, na.rm = TRUE)) %>% 
  filter(price == min_price)
```

